### ISSUE TITLE
Add UI for choosing shading/lighting style

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#10]

**Comment by mtwoodard** [comment]
I added the gui controller, I think that the shader will need to be concatenated again upon change. It also may be smart to separate the shading/lighting out to another shader file.

**Comment by mtwoodard** [comment]
Actually I thought it out a bit more we can pass a simple int value to the shader to change the lighting on the fly I'll add it to the globals

**Comment by henryseg** [comment]
This is now working.
