### ISSUE TITLE
Implement Phong reflection model for lighting

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#15]
Currently we have a hacky system that calculates the appropriate (Lorentz) dot products, but doesn't combine them in a sensible way.

**Comment by henryseg** [comment]
Do https://en.wikipedia.org/wiki/Phong_reflection_model

Would be interesting to also add option for brightness fall off with distance from light source. Linear fall off vs the true exponential value (proportional to area of sphere around the light source).

Also maybe look at doing ray marching back to the light source from the surface to do proper shadows.

**Comment by mtwoodard** [comment]
Needs to be refactored but it is working
