### ISSUE TITLE
Add support for Vive controllers

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#16]
Detect position, have some indicator of position visible in the simulation.
Be able to use buttons etc for input.

**Comment by mtwoodard** [comment]
I added a javascript file from Mr. Doob should be able to handle inputs from the Vive controller. It will need to be changed so that it works with our raymarch system in order to show a model.

**Comment by mtwoodard** [comment]
I'll be tracking this now under issue #30 since I've gotten a list of tasks there to work on.
