### ISSUE TITLE
Do headset lens distortion

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#17]
Predistort the positions of the rays so that they undo the distortion from the headset lenses. From http://doc-ok.org/?p=1677, the data of the distortion mesh should be available to us?

**Comment by mtwoodard** [comment]
https://www.reddit.com/r/OSVR/comments/4c0e20/osvr_webvr_a_developers_guide/

**Comment by mtwoodard** [comment]
https://github.com/OSVR/OSVR-Docs/blob/master/Integrating-Game-Engines/WebVR/webvr.md

**Comment by mtwoodard** [comment]
https://immersive-web.github.io/webxr/#xrview

**Comment by mtwoodard** [comment]
Currently in headset I don't think there is much of an issue with distortion from the lenses. It may be wise to revisit this in the future but as of now I'll be closing this issue.
