### ISSUE TITLE
Background jumps color when moving between cubes

### ISSUE THREAD

**Issue by roice3** [mtwoodard/hypVR-Ray#2]
I bet this can be fixed by making gluing between cubes a consistent manifold.

**Comment by henryseg** [comment]
The code is now tracking a matrix (cellBoost) that undoes the various teleportations of the camera back into the cube. This is passed into the shader for objects that are supposed to be global, but we could also use it to move the endpoints of geodesics used to calculate the background colours.

**Comment by henryseg** [comment]
Fixed with latest update.
