### ISSUE TITLE
Add options for light intensity fall off

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#27]
Get distances from light to object (distance_LO) and object to camera (distance_OC). Then have some choices of fall off function for light intensities based on distance. E.g. f(dist) = 1/(dist^2) is inverse square fall off, which is correct for 3d euclidean space. Then the light intensities (both diffuse and specular (?)) get multiplied by 

f(distance_LO)*f(distance_OC) 

(Since there is fall off from the light to the object and from the object to the camera.)

Choices for f:
f(d) = 1 (no fall off, should be same as what we are doing now)
f(d) = 1/d (linear fall off)
f(d) = 1/d^2 (inverse square)
f(d) = 1/(cosh(2*d) - 1) ("physically correct" fall off for hyperbolic space, according to surface area calculation given at https://math.stackexchange.com/questions/1445278/what-is-the-volume-of-the-sphere-in-hyperbolic-space)

The last few cases we probably want to add a constant term, so it's really f(d) = k/d, where k is some magic number chosen to make it look ok.

**Comment by mtwoodard** [comment]
Should be implemented now. I also added an attenuation component (i.e. w value of the light intensity vector) which is working for linear and inverse square, however the physical model changes too dramatically.
