### ISSUE TITLE
Refactor Global Naming Conventions

### ISSUE THREAD

**Issue by mtwoodard** [mtwoodard/hypVR-Ray#32]
For readability I think it would be wise to refactor all JavaScript global variables to the same formatting. There isn't a defined coding convention so I suggest ALL_CAPS for our global variables. I noticed there was two variables named the same but in different scopes during my refactor of the VRControlsHyperbolic file, this should solve this issue.

**Comment by roice3** [comment]
I agree 100%. I've experienced difficulty because we haven't named our variables by scope.

Another option to consider that I like is prepending globals with g_ and class-level variables with m_.

**Comment by mtwoodard** [comment]
I just merged the WIP branch into master so now the global variables should have the g_ prefix. I've currently left alone class level variables as of now.
