### ISSUE TITLE
Only {4,3,6} working

### ISSUE THREAD

**Issue by roice3** [mtwoodard/hypVR-Ray#4]
The rendering looks broken for r != 6.

Henry had worked this out already, so the other values of r must have been broken by some intervening changes.

**Comment by henryseg** [comment]
How is it broken for you? Changing the scene from Sphere_horosphere to Sphere_plane may help for the other values of r?

**Comment by roice3** [comment]
I see, in fragmentInclude.glsl, horosphereSize is hardcoded for the {4,3,6} and planeOffset hardcoded for {4,3,7}.  So e.g. Sphere_plane works for the {4,3,7} but gives bad results for the {4,3,8} (pic below).  So we'll just need to make those sizes uniforms to pass into the shader. It would probably be nicer for the user to not have separate sphere and plane options, and to default to the correct option depending on the honeycomb.

![image](https://user-images.githubusercontent.com/1696416/37296447-06c47490-25e9-11e8-9a3c-068db675b022.png)

**Comment by henryseg** [comment]
Ah I see. In "sphere_plane" the geodesic plane is (I believe) set to give the "head" of the dual cell, no matter what value of p is used. But the sphere radius is hard coded to work reasonably for {4,3,7}. Yes, these should be fed in as uniforms. But what choices should we make for the sphere radius? Is there a natural choice to make?

**Comment by roice3** [comment]
This is fixed now, and works well in most all cases.  One example where it doesn't work is Sphere_plane doesn't produce goodness for the 436. What I think would be better would be to not have scenes that pick the cutting from a vertex, because we can automatically pick the correct cut (sphere, horosphere, plane) based on the vertex figure. I think I'll open an issue for that.
