### ISSUE TITLE
Generalize dot/normalize/others functions (Javascript)

### ISSUE THREAD

**Issue by mtwoodard** [mtwoodard/hypVR-Ray#40]

**Comment by mtwoodard** [comment]
Are we wanting to eliminate the need for the Euclidean and Hyperbolic files all together? I figure if we do it will make it slower to load initially however switching between the different geometries would be much faster.

**Comment by henryseg** [comment]
There will still be some differences between different geometries - how dot is defined, and so on. It makes sense to put those functions in separate files for different geometries.

**Comment by mtwoodard** [comment]
I was wondering if we wanted to switch over to only using the THREE vector definition on the JavaScript side. Currently we have certain implementations for both array based and THREE based input, switching over would allow us to remove some of the bloat.

**Comment by henryseg** [comment]
As long as we can get the same functionality, makes sense to me.

**Comment by mtwoodard** [comment]
HypMath is now completely based in THREE and also got refactored
