### ISSUE TITLE
Add key/UI button to reset position to the origin

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#44]
Reset currentBoost to the identity, and reset the cellBoost (?) matrices as well.

**Comment by henryseg** [comment]
Related to this: When we switch the edge degree, I think we are not updating cellBoost, which means that the global objects (eg lights) end up far from you. I'm not sure what the right way to recalculate cellBoost is when we change the edge degree - maybe best to just set to the identity.

**Comment by mtwoodard** [comment]
This should be working now, the button I added should reset currentBoost/cellBoost/invCellBoost.
