### ISSUE TITLE
Flickering background coloured noise on iOS

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#5]
On iOS we seem to bail out of the ray marching for loop early (for some noisy flickering collection of pixels) resulting in us getting the background colour.

![img_8036](https://user-images.githubusercontent.com/10263961/37269372-59e27464-260d-11e8-9230-c295eedbbaef.PNG)

**Comment by mtwoodard** [comment]
Going to close this and keep open #21 as our hub for mobile issues.
