### ISSUE TITLE
Fix simplex cuts for r = 5, r >= 7

### ISSUE THREAD

**Issue by henryseg** [mtwoodard/hypVR-Ray#50]
For r=5 it looks like something is wrong with the geometry = 1 case. Perhaps HalfKleinCubeWidth is not getting set properly?

For r >= 7, rays that should be going off to infinity are not - they seem to be getting hitwhich = 3 when they shouldn't.

**Comment by roice3** [comment]
I made quite a few changes the last few days to this section of code, and think it has been fixed along the way. Can you see if this is still an issue for you?

**Comment by henryseg** [comment]
Looks like it's working great to me! Something odd happens when the edge thickness is very large for r=5. Some spheres get bigger, and poke new holes through walls. Not that that's a bad thing, just interesting.

**Comment by roice3** [comment]
Ah, interesting. I stared at this for a while and convinced myself it is correct (at least with how the calculation is done now for the two sphere sizes). It's only happening on the vertex-centered chambers. Those spherical cutouts end up crashing into the cell-centered cutouts.

Anyway, I'm going to go ahead and close this issue.
