### ISSUE TITLE
SteamVR freaks out when VR is enabled.

### ISSUE THREAD

**Issue by mtwoodard** [mtwoodard/hypVR-Ray#66]
We're experiencing a problem when using the VR capabilities of the project. Sometime, usually less than a minute, after starting VR SteamVR will begin to flash between responsive and unresponsive while the framerate tanks. Even when closing the program and restarting everything (i.e. computer, steamvr, browser) the problem will persist the next time VR is enabled. The only way we've found to fix the issue is to completely reinstall SteamVR.

Note that this problem also affects previous versions which were not experiencing it such as the one hosted [here.](http://www.michaelwoodard.net/hypVR-Ray2/)

**Comment by mtwoodard** [comment]
We've also noted that this problem exists on both Firefox and Chromium. It'd be a good idea to check what versions we're running and that we're up to date on both. As well as check that we are running the 64-bit versions and not the 32-bit.

**Comment by henryseg** [comment]
I was able to run all of our recent versions of the code without any trouble on an older version of Firefox - specifically https://ftp.mozilla.org/pub/firefox/releases/60.2.0esr/win64/en-US/, which is from June 2018. This was also running on a version of SteamVR from May 2018. Something between that version of Firefox and the current version broke.

**Comment by mtwoodard** [comment]
Apparently this was an issue with Firefox. More information can be found [here.](https://stackoverflow.com/questions/54540996/webvr-not-working-with-latest-version-of-firefox)
