### ISSUE TITLE
Automatically pick the correct vertex-centered cut based on the vertex figure

### ISSUE THREAD

**Issue by roice3** [mtwoodard/hypVR-Ray#7]
The two scene options Sphere_horosphere and Sphere_plane are a bit awkward because we can automatically pick the correct cut for a vertex (sphere, horosphere, plane) depending on whether the vertex figure is spherical, euclidean, or hyperbolic.  Though it can produce cool looking results, it doesn't really make sense to construct a horosphere cut when you have a hyperbolic vertex figure.

Another option would be to have separate scenes for whether to include cell-centered cuts, vertex-centered cuts, or both.

**Comment by henryseg** [comment]
I agree, let's have it choose the correct cut for the geometry. The only problem is deciding what it should be called...

**Comment by roice3** [comment]
Issue #19 is relevant to this.

**Comment by roice3** [comment]
I called this "Simplex_cuts", though it is easy to change if there are better thoughts. I don't like Simplex_cuts much, but couldn't think of anything better that was short.
